In [5]:
import numpy as np
xarr=np.array([1,2,3,4,5,6])
yarr=np.array([7,8,9,10,11,12])

In [6]:
cond=np.array([True,False,True,True,False,True])

In [13]:
result=np.where(cond,xarr,yarr)

In [14]:
result

array([ 1,  8,  3,  4, 11,  6])

In [15]:
arr=np.random.randn(4,4)

In [18]:
cond=arr>0
cond

array([[ True, False,  True, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [False, False, False,  True]])

In [20]:
result=np.where(cond,2,-2)

In [21]:
result

array([[ 2, -2,  2, -2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2],
       [-2, -2, -2,  2]])

|

Mathematical and statistical methods

|

In [22]:
arr=np.random.randn(5,4)

In [23]:
arr

array([[-0.68583893,  1.09641482, -1.22301041,  0.15594188],
       [-0.74844018, -1.11608081, -1.34019222,  2.07831182],
       [ 0.29595218,  0.42062017, -0.10390904, -0.63722947],
       [ 0.75887604,  0.69316398,  1.50532059, -1.2634479 ],
       [-0.45531373, -0.72055007, -0.37865305,  0.66688075]])

In [25]:
arr.mean()

-0.050059179233389296

In [26]:
np.mean(arr)

-0.050059179233389296

In [27]:
np.sum(arr)

-1.001183584667786

In [28]:
np.mean(arr,axis=0)

array([-0.16695292,  0.07471362, -0.30808883,  0.20009142])

In [29]:
np.sum(arr,axis=1)

array([-0.65649264, -1.12640139, -0.02456615,  1.69391271, -0.88763611])

In [30]:
arr=np.random.randn(4,3)

In [31]:
arr

array([[ 0.05206295,  1.37282345, -0.62264416],
       [-0.32413805, -1.81582774, -1.00815127],
       [-1.84608974, -1.81640131, -0.06967151],
       [-0.96645711,  0.45508938,  1.57971023]])

In [32]:
np.std(arr,axis=1)

array([0.82875603, 0.60967692, 0.8305024 , 1.04182184])

In [33]:
np.var(arr,axis=1)

array([0.68683655, 0.37170595, 0.68973423, 1.08539274])

In [34]:
np.argmax(arr)

11

In [35]:
np.argmin(arr)

6

In [36]:
np.min(arr)

-1.8460897357984036

In [37]:
np.max(arr)

1.5797102345971923

In [38]:
np.cumsum(arr,axis=1)

array([[ 0.05206295,  1.4248864 ,  0.80224223],
       [-0.32413805, -2.13996579, -3.14811706],
       [-1.84608974, -3.66249104, -3.73216256],
       [-0.96645711, -0.51136773,  1.06834251]])

|

Methods for Boolean Arrays

|

In [41]:
arr=np.random.randn(100)

In [43]:
(arr>0).sum()

52

|

Sorting

|

In [45]:
arr=np.random.randn(6)

In [46]:
arr

array([ 0.23505617, -0.42023509,  0.07792767, -0.13352609, -0.69995008,
       -0.11840472])

In [47]:
arr.sort()

In [48]:
arr

array([-0.69995008, -0.42023509, -0.13352609, -0.11840472,  0.07792767,
        0.23505617])

In [56]:
arr=np.random.randn(5,3)

In [57]:
arr

array([[ 1.11120838, -1.44745751,  0.88126068],
       [-0.60980568, -0.00681901, -1.65754183],
       [-1.68058276,  2.1712182 , -0.66259526],
       [-1.2887953 , -0.67281147, -0.25819642],
       [-0.69972902, -0.05597007, -1.27279283]])

In [58]:
np.sort(arr,axis=1)

array([[-1.44745751,  0.88126068,  1.11120838],
       [-1.65754183, -0.60980568, -0.00681901],
       [-1.68058276, -0.66259526,  2.1712182 ],
       [-1.2887953 , -0.67281147, -0.25819642],
       [-1.27279283, -0.69972902, -0.05597007]])

In [59]:
arr

array([[ 1.11120838, -1.44745751,  0.88126068],
       [-0.60980568, -0.00681901, -1.65754183],
       [-1.68058276,  2.1712182 , -0.66259526],
       [-1.2887953 , -0.67281147, -0.25819642],
       [-0.69972902, -0.05597007, -1.27279283]])

In [62]:
names=np.array(["ter","cut","ter","ter","cut"])

In [64]:
np.unique(arr,axis=1)

array([[-1.44745751,  0.88126068,  1.11120838],
       [-0.00681901, -1.65754183, -0.60980568],
       [ 2.1712182 , -0.66259526, -1.68058276],
       [-0.67281147, -0.25819642, -1.2887953 ],
       [-0.05597007, -1.27279283, -0.69972902]])

In [65]:
from numpy.linalg import inv,qr

In [66]:
X=np.random.randn(5,4)

In [68]:
mat=np.dot(X.T,X)

In [69]:
inv(mat)

array([[ 0.30965317,  0.38561799,  0.201781  , -0.29515001],
       [ 0.38561799,  0.8784222 ,  0.41982789, -0.54206239],
       [ 0.201781  ,  0.41982789,  0.28543861, -0.30803261],
       [-0.29515001, -0.54206239, -0.30803261,  0.52056901]])

In [70]:
mat

array([[ 8.14924955, -1.94481168, -0.27561807,  2.43222797],
       [-1.94481168,  5.033862  , -4.32272982,  1.58118188],
       [-0.27561807, -4.32272982, 13.91665294,  3.57732601],
       [ 2.43222797,  1.58118188,  3.57732601,  7.06324112]])

In [71]:
np.trace(mat)

34.1630056072067

In [77]:
from numpy.linalg import eig,svd

In [74]:
eig(mat)

(array([ 0.5902621 , 16.64820867,  9.48603516,  7.43849967]),
 array([[-0.35498085, -0.13187909,  0.83087705, -0.40772518],
        [-0.69402079,  0.30980876,  0.06973224,  0.6461355 ],
        [-0.3684376 , -0.88781352, -0.26936585,  0.05901631],
        [ 0.50653476, -0.3137094 ,  0.48189499,  0.64248437]]))

In [75]:
qr(mat)

(array([[-0.93365192, -0.03870425,  0.10074887, -0.3415344 ],
        [ 0.22281526, -0.67397676, -0.32041487, -0.62725035],
        [ 0.03157731,  0.65742735, -0.66313012, -0.35644156],
        [-0.27865809, -0.33473361, -0.66891136,  0.60237917]]),
 array([[ -8.72835947,   2.36028915,  -1.26323926,  -3.77380981],
        [  0.        ,  -6.68858905,  10.87582407,  -1.17228961],
        [  0.        ,   0.        , -10.2641671 ,  -7.35850486],
        [  0.        ,   0.        ,   0.        ,   1.15715528]]))

In [78]:
svd(mat)

(array([[-0.13187909, -0.83087705,  0.40772518, -0.35498085],
        [ 0.30980876, -0.06973224, -0.6461355 , -0.69402079],
        [-0.88781352,  0.26936585, -0.05901631, -0.3684376 ],
        [-0.3137094 , -0.48189499, -0.64248437,  0.50653476]]),
 array([16.64820867,  9.48603516,  7.43849967,  0.5902621 ]),
 array([[-0.13187909,  0.30980876, -0.88781352, -0.3137094 ],
        [-0.83087705, -0.06973224,  0.26936585, -0.48189499],
        [ 0.40772518, -0.6461355 , -0.05901631, -0.64248437],
        [-0.35498085, -0.69402079, -0.3684376 ,  0.50653476]]))

In [89]:
arr=np.random.randint(-10,30,size=(4,5),dtype=np.int64)

In [90]:
arr

array([[ 14,  -1,  27,  25,  17],
       [ 20,  26,   2,  -1,  13],
       [ 17,  27,  -1,  12,  20],
       [ 22,  -5, -10,   3,  10]], dtype=int64)