Arthimatic with numpy arrays

In [3]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [11]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
arr2=np.array([[1,6,9],[8,4,7]])

In [15]:
arr2>arr

array([[False,  True,  True],
       [ True, False,  True]])

Basic Indexing and Slicing

In [17]:
arr=np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[5]

5

In [20]:
arr[5:8]

array([5, 6, 7])

In [21]:
arr[5:8]=12

In [22]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr[:]=64

In [24]:
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [29]:
arr_copied=arr[:].copy()[:]=65

In [30]:
arr_copied

65

In [32]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
arr2d[1]

array([4, 5, 6])

In [34]:
arr2d[1][0]

4

In [35]:
arr2d[1,0]

4

In [36]:
arr3d=np.array([[[1,2,3],[4,5,5]],[[7,8,9],[10,11,12]]])

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 5]])

In [39]:
arr3d[0]=42

In [40]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0,1]

array([42, 42, 42])

In [42]:
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [43]:
arr[1:6]

array([64, 64, 64, 64, 64])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
arr2d[1,:2]

array([4, 5])

In [55]:
arr2d[:,2:]

array([[3],
       [6],
       [9]])