Fancy Indexing

In [10]:
import numpy as np


In [14]:
arr=np.empty((8,4))

In [15]:
arr

array([[6.23042070e-307, 1.86918699e-306, 6.23059386e-307,
        1.42417629e-306],
       [1.02361614e-306, 1.33512376e-306, 1.33511290e-306,
        1.78018403e-306],
       [1.37962388e-306, 1.37961913e-306, 1.86921415e-306,
        8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.78018403e-306],
       [1.37962388e-306, 1.37961913e-306, 7.56589622e-307,
        1.95818994e-306],
       [1.37961302e-306, 1.78019082e-306, 6.23037657e-307,
        1.29061685e-306],
       [6.23061763e-307, 9.34607074e-307, 9.34605037e-307,
        1.24610723e-306],
       [1.11260144e-306, 6.89812281e-307, 2.22522596e-306,
        1.42410974e-306]])

In [16]:
for i in range(8):
    arr[i]=i

In [17]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [18]:
arr=arr.astype(np.int64)

In [19]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]], dtype=int64)

In [20]:
arr[[3,5,6]]

array([[3, 3, 3, 3],
       [5, 5, 5, 5],
       [6, 6, 6, 6]], dtype=int64)

In [21]:
arr=np.arange(32).reshape((8,4))

In [22]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [24]:
arr[[1,5,7,2],[2,3,0,1]]

array([ 6, 23, 28,  9])

Transposing Arrays and Swapping Axes

In [26]:
arr=np.arange(15).reshape((3,5))

In [27]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [29]:
arr=np.random.randn(6,3)

In [37]:
arr

array([[-0.89932436,  0.21416416, -0.57130626],
       [ 0.26434499, -0.13622279,  0.8105614 ],
       [ 1.09429995, -1.56206168,  0.04420618],
       [-0.56858377,  0.55574641,  0.66102777],
       [ 1.9266864 , -0.15776932,  0.67130293],
       [ 0.23151355,  0.70166242,  0.36506352]])

In [38]:
np.dot(arr.T,arr)

array([[ 6.16516145, -2.39549292,  1.77849002],
       [-2.39549292,  3.33053502,  0.21578112],
       [ 1.77849002,  0.21578112,  2.00623153]])

In [39]:
arr=np.arange(16).reshape((2,2,4))

Unversal Functions

In [41]:
arr=np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
x=np.random.randn(8)

In [46]:
x

array([-0.1413754 , -0.86255014,  0.96447136,  1.04049737, -0.60431578,
        1.39939836,  0.67574409, -1.14027662])

In [47]:
y=np.random.randn(8)

In [48]:
y

array([-1.04687639, -0.16380236, -2.14491823,  0.51556474,  1.76221052,
        0.95554943,  0.19122201,  1.41942455])

In [49]:
np.maximum(x,y)

array([-0.1413754 , -0.16380236,  0.96447136,  1.04049737,  1.76221052,
        1.39939836,  0.67574409,  1.41942455])

In [52]:
arr=np.random.randn(7)*5

In [53]:
arr

array([-5.58555941,  1.57041419, -1.21175821,  1.09269494,  1.76039691,
       -1.86842055,  0.36680779])

In [54]:
remin,whole_part=np.modf(arr)

In [56]:
remin

array([-0.58555941,  0.57041419, -0.21175821,  0.09269494,  0.76039691,
       -0.86842055,  0.36680779])

In [57]:
whole_part

array([-5.,  1., -1.,  1.,  1., -1.,  0.])

In [58]:
arr=np.random.randn(4,5)

In [59]:
arr

array([[ 1.55654794, -0.78805329, -2.58010225,  0.04531408,  1.63710549],
       [-2.31988931, -1.12559045, -0.43166927,  0.91386171, -1.16422258],
       [-0.98483379, -0.95304513,  1.73743184, -0.22119168, -0.57620019],
       [-0.25762725,  0.10465647, -1.28332057, -0.81169433, -0.41188897]])

In [60]:
np.abs(arr)

array([[1.55654794, 0.78805329, 2.58010225, 0.04531408, 1.63710549],
       [2.31988931, 1.12559045, 0.43166927, 0.91386171, 1.16422258],
       [0.98483379, 0.95304513, 1.73743184, 0.22119168, 0.57620019],
       [0.25762725, 0.10465647, 1.28332057, 0.81169433, 0.41188897]])

In [61]:
np.fabs(arr)

array([[1.55654794, 0.78805329, 2.58010225, 0.04531408, 1.63710549],
       [2.31988931, 1.12559045, 0.43166927, 0.91386171, 1.16422258],
       [0.98483379, 0.95304513, 1.73743184, 0.22119168, 0.57620019],
       [0.25762725, 0.10465647, 1.28332057, 0.81169433, 0.41188897]])

In [62]:
np.square(arr)

array([[2.42284149e+00, 6.21027993e-01, 6.65692763e+00, 2.05336569e-03,
        2.68011440e+00],
       [5.38188642e+00, 1.26695387e+00, 1.86338361e-01, 8.35143231e-01,
        1.35541422e+00],
       [9.69897590e-01, 9.08295028e-01, 3.01866941e+00, 4.89257578e-02,
        3.32006660e-01],
       [6.63717983e-02, 1.09529758e-02, 1.64691170e+00, 6.58847688e-01,
        1.69652520e-01]])

In [63]:
np.exp(arr)

array([[4.74242183, 0.45472916, 0.07576626, 1.04635645, 5.14026942],
       [0.09828446, 0.32446083, 0.64942412, 2.49393482, 0.31216525],
       [0.3735013 , 0.38556514, 5.68273052, 0.80156302, 0.56202992],
       [0.77288327, 1.11032911, 0.27711559, 0.44410497, 0.66239782]])

In [64]:
np.log(arr)

<ipython-input-64-a67b4ae04e95>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[ 0.44247051,         nan,         nan, -3.09413752,  0.49292974],
       [        nan,         nan,         nan, -0.09007602,         nan],
       [        nan,         nan,  0.55240807,         nan,         nan],
       [        nan, -2.25707205,         nan,         nan,         nan]])

In [66]:
np.log10(arr)

<ipython-input-66-4473232fb1a0>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([[ 0.1921625 ,         nan,         nan, -1.34376685,  0.21407667],
       [        nan,         nan,         nan, -0.03911952,         nan],
       [        nan,         nan,  0.23990778,         nan,         nan],
       [        nan, -0.98023394,         nan,         nan,         nan]])

In [67]:
np.sign(arr)

array([[ 1., -1., -1.,  1.,  1.],
       [-1., -1., -1.,  1., -1.],
       [-1., -1.,  1., -1., -1.],
       [-1.,  1., -1., -1., -1.]])

In [68]:
np.ceil(arr)

array([[ 2., -0., -2.,  1.,  2.],
       [-2., -1., -0.,  1., -1.],
       [-0., -0.,  2., -0., -0.],
       [-0.,  1., -1., -0., -0.]])

In [69]:
np.floor(arr)

array([[ 1., -1., -3.,  0.,  1.],
       [-3., -2., -1.,  0., -2.],
       [-1., -1.,  1., -1., -1.],
       [-1.,  0., -2., -1., -1.]])

In [70]:
np.isnan(arr)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [71]:
np.cos(arr)

array([[ 0.01424791,  0.70522683, -0.84646249,  0.99897349, -0.06626059],
       [-0.68097483,  0.43064369,  0.90826861,  0.61069234,  0.3954647 ],
       [ 0.55300161,  0.57920344, -0.16586541,  0.9756367 ,  0.83853899],
       [ 0.96699725,  0.99452851,  0.28353247,  0.68827026,  0.91636623]])

In [72]:
np.sin(arr)

array([[ 0.99989849, -0.70898175, -0.53244836,  0.04529857,  0.99780235],
       [-0.73230682, -0.90252203, -0.41838753,  0.79186796, -0.91848117],
       [-0.83318019, -0.81518303,  0.9861484 , -0.21939242, -0.54484159],
       [-0.25478683,  0.10446552, -0.95896264, -0.72545437, -0.40034103]])

In [74]:
np.tan(arr)

array([[ 7.01786305e+01, -1.00532441e+00,  6.29027706e-01,
         4.53451193e-02, -1.50587613e+01],
       [ 1.07538017e+00, -2.09575117e+00, -4.60642950e-01,
         1.29667248e+00, -2.32253641e+00],
       [-1.50665057e+00, -1.40742092e+00, -5.94547338e+00,
        -2.24871023e-01, -6.49751049e-01],
       [-2.63482473e-01,  1.05040247e-01, -3.38219686e+00,
        -1.05402545e+00, -4.36878851e-01]])

In [79]:
arr1=np.random.randn(3,4)

In [80]:
arr1

array([[-0.93954055,  1.70153738,  0.30676732,  0.50372567],
       [ 2.25876438, -0.10878907, -0.0791485 , -0.56688222],
       [ 1.15913835, -0.12787873, -0.06400906,  0.88020772]])

In [81]:
arr2=np.random.randn(3,4)

In [82]:
arr2

array([[ 0.82327783,  2.19287384,  0.68020506, -2.20026801],
       [ 0.12992197, -0.25937488, -1.56289453, -1.81113711],
       [ 0.20198436, -0.63664865,  1.0674642 , -0.72959023]])

In [83]:
np.add(arr1,arr2)

array([[-0.11626272,  3.89441122,  0.98697238, -1.69654234],
       [ 2.38868635, -0.36816395, -1.64204304, -2.37801933],
       [ 1.36112271, -0.76452738,  1.00345514,  0.15061749]])

In [85]:
np.subtract(arr1,arr2)

array([[-1.76281838, -0.49133647, -0.37343774,  2.70399368],
       [ 2.12884241,  0.1505858 ,  1.48374603,  1.24425489],
       [ 0.95715399,  0.50876992, -1.13147327,  1.60979794]])

In [86]:
np.multiply(arr1,arr2)

array([[-0.7735029 ,  3.7312568 ,  0.20866468, -1.10833148],
       [ 0.29346312,  0.02821715,  0.12370076,  1.02670142],
       [ 0.23412782,  0.08141382, -0.06832738, -0.64219095]])

In [87]:
np.divide(arr1,arr2)

array([[-1.1412193 ,  0.77593947,  0.45099241, -0.22893833],
       [17.38554574,  0.41942795,  0.05064225,  0.31299796],
       [ 5.738753  ,  0.20086232, -0.05996366, -1.20644122]])

In [88]:
np.power(arr1,arr2)

<ipython-input-88-5c0d058082be>:1: RuntimeWarning: invalid value encountered in power
  np.power(arr1,arr2)


array([[       nan, 3.20779253, 0.44763594, 4.52119069],
       [1.11166929,        nan,        nan,        nan],
       [1.03027775,        nan,        nan, 1.09756466]])

In [89]:
np.maximum(arr1,arr2)

array([[ 0.82327783,  2.19287384,  0.68020506,  0.50372567],
       [ 2.25876438, -0.10878907, -0.0791485 , -0.56688222],
       [ 1.15913835, -0.12787873,  1.0674642 ,  0.88020772]])

Array-Oriented progreamming with Arrays