Time for Computing Checking


In [60]:
import numpy as np

In [2]:
my_arr=np.arange(100000)

In [3]:
my_list=list(range(100000))

In [12]:
%time
for _ in range(10):
    my_arr2=my_arr*2

Wall time: 0 ns


|
|
Numpy_Arrays
|
|


In [14]:
data=np.random.randn(2,3)
data

array([[ 0.28363341, -0.94122153,  0.5085185 ],
       [-1.60700318, -2.13386843, -2.70049723]])

In [15]:
data*10

array([[  2.83633408,  -9.41221531,   5.08518503],
       [-16.07003175, -21.33868432, -27.00497225]])

In [16]:
data+data

array([[ 0.56726682, -1.88244306,  1.01703701],
       [-3.21400635, -4.26773686, -5.40099445]])

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

In [19]:
data.shape

(2, 3)

In [21]:
data.dtype

dtype('float64')

Creating Ndarrays

In [22]:
data_1=[1,2,3,4,5,6,7,8]
arr1=np.array(data_1)

In [23]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
data2=[[2,85,8,9,5],[4,8,9,6,7]]

In [33]:
arr2=np.array(data2)

In [34]:
arr2

array([[ 2, 85,  8,  9,  5],
       [ 4,  8,  9,  6,  7]])

In [27]:
arr2.ndim

2

In [28]:
arr2.shape

(2, 5)

In [35]:
arr2.dtype

dtype('int32')

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones_like((2,3))

array([1, 1])

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.zeros_like((2,3))

array([0, 0])

Data Types for ndarrays

In [53]:
arr=np.array([1,2,3,4,5,65])

In [54]:
arr.dtype

dtype('int32')

In [55]:
float_arr=arr.astype(np.float64)

In [56]:
float_arr.dtype

dtype('float64')

In [61]:
a=np.array([1,2,3,5,4])

In [62]:
a.dtype

dtype('int32')

In [63]:
a.astype(np.float64)

array([1., 2., 3., 5., 4.])

In [64]:
b=np.array([3.9,3.8,9.4,6.5,2.5])

In [65]:
b.astype(np.int32)

array([3, 3, 9, 6, 2])

In [66]:
b=np.array(['3.9','3.8'])

In [67]:
b.astype(np.float64)

array([3.9, 3.8])